-- Datos aromáticos que ya estaban en app.js. No realiza ninguna descarga externa.
-- Aplicar SOLO si la autorización de Fragrantica cubre almacenamiento y uso comercial.
-- Sustituir la referencia de licencia en perfume_sources cuando se tenga su folio.

insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'sauvage', 'Fragrantica', 'https://www.fragrantica.es/perfume/Dior/Sauvage-Eau-de-Parfum-48100.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'sauvage' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'acqua-di-gio', 'Fragrantica', 'https://www.fragrantica.es/perfume/Giorgio-Armani/Acqua-di-Gio-410.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'acqua-di-gio' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'light-blue', 'Fragrantica', 'https://www.fragrantica.es/perfume/Dolce-Gabbana/Light-Blue-485.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'light-blue' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'dylan-blue', 'Fragrantica', 'https://www.fragrantica.es/perfume/Versace/Versace-Pour-Homme-Dylan-Blue-40031.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'dylan-blue' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'libre', 'Fragrantica', 'https://www.fragrantica.es/perfume/Yves-Saint-Laurent/Libre-56077.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'libre' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'la-vie-est-belle', 'Fragrantica', 'https://www.fragrantica.es/perfume/Lancome/La-Vie-Est-Belle-14982.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'la-vie-est-belle' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'eros', 'Fragrantica', 'https://www.fragrantica.es/perfume/Versace/Eros-Eau-de-Parfum-62762.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'eros' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'bleu-de-chanel', 'Fragrantica', 'https://www.fragrantica.es/perfume/Chanel/Bleu-de-Chanel-9099.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'bleu-de-chanel' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'terre-d-hermes', 'Fragrantica', 'https://www.fragrantica.es/perfume/Hermes/Terre-d-Hermes-17.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'terre-d-hermes' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'boss-bottled', 'Fragrantica', 'https://www.fragrantica.es/perfume/Hugo-Boss/Boss-Bottled-383.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'boss-bottled' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'oud-for-glory', 'Fragrantica', 'https://www.fragrantica.es/perfume/Lattafa-Perfumes/Bade-e-Al-Oud-Oud-for-Glory-64948.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'oud-for-glory' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'oud-mood', 'Fragrantica', 'https://www.fragrantica.es/perfume/Lattafa-Perfumes/Oud-Mood-46814.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'oud-mood' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select '1-million', 'Fragrantica', 'https://www.fragrantica.es/perfume/Paco-Rabanne/1-Million-3747.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = '1-million' and is_primary);
insert into public.perfume_sources (perfume_id, publisher, source_url, rights_basis, license_reference, is_primary, checked_at)
select 'coco-mademoiselle', 'Fragrantica', 'https://www.fragrantica.es/perfume/Chanel/Coco-Mademoiselle-611.html', 'licencia', 'Autorización comercial declarada por el propietario el 2026-10-03; registrar folio', true, date '2026-10-02'
where not exists (select 1 from public.perfume_sources where perfume_id = 'coco-mademoiselle' and is_primary);

insert into public.notes (name) values
  ('bergamota'),
  ('pimienta de Sichuan'),
  ('lavanda'),
  ('anís estrellado'),
  ('nuez moscada'),
  ('ambroxan'),
  ('vainilla'),
  ('lima'),
  ('limón'),
  ('jazmín'),
  ('naranja'),
  ('mandarina'),
  ('neroli'),
  ('notas marinas'),
  ('calone'),
  ('romero'),
  ('durazno'),
  ('fresia'),
  ('jacinto'),
  ('violeta'),
  ('ciclamen'),
  ('cilantro'),
  ('rosa'),
  ('reseda'),
  ('almizcle blanco'),
  ('cedro'),
  ('musgo de roble'),
  ('pachulí'),
  ('ámbar'),
  ('limón siciliano'),
  ('manzana'),
  ('campanilla'),
  ('bambú'),
  ('rosa blanca'),
  ('almizcle'),
  ('bergamota de Calabria'),
  ('notas acuáticas'),
  ('toronja'),
  ('hojas de higuera'),
  ('pimienta negra'),
  ('hojas de violeta'),
  ('papiro de Egipto'),
  ('incienso'),
  ('haba tonka'),
  ('azafrán'),
  ('grosellas negras'),
  ('petit grain'),
  ('flor de azahar'),
  ('vainilla de Madagascar'),
  ('ámbar gris'),
  ('pera'),
  ('iris'),
  ('praliné'),
  ('menta'),
  ('manzana acaramelada'),
  ('geranio'),
  ('esclarea'),
  ('sándalo'),
  ('naranja amarga'),
  ('cuero'),
  ('pimienta rosa'),
  ('jengibre'),
  ('Iso E Super'),
  ('vetiver'),
  ('ládano'),
  ('pimienta'),
  ('pelargonio'),
  ('sílex'),
  ('benjuí'),
  ('ciruela'),
  ('canela'),
  ('caoba'),
  ('clavel'),
  ('olivo'),
  ('madera de oud'),
  ('pimienta de Jamaica'),
  ('caramelo'),
  ('notas florales'),
  ('notas amaderadas'),
  ('resinas'),
  ('mandarina roja'),
  ('notas especiadas'),
  ('pachulí hindú'),
  ('rosa turca'),
  ('mimosa'),
  ('ylang-ylang'),
  ('opopónaco')
on conflict (name) do nothing;

insert into public.accords (name, color_rgb) values
  ('fresco especiado', '131,201,40'),
  ('cítrico', '249,255,82'),
  ('ámbar', '188,77,16'),
  ('lavanda', '155,125,184'),
  ('almizclado', '231,216,234'),
  ('aromático', '55,160,137'),
  ('herbal', '108,164,127'),
  ('anís', '195,215,179'),
  ('marino', '14,82,155'),
  ('florales', '255,95,141'),
  ('amaderado', '119,68,20'),
  ('fresco', '155,229,237'),
  ('afrutados', '252,75,41'),
  ('atalcado', '238,221,204'),
  ('verde', '14,140,29'),
  ('acuático', '99,204,226'),
  ('cálido especiado', '204,51,0'),
  ('floral blanco', '237,242,251'),
  ('avainillado', '255,254,192'),
  ('dulce', '238,54,59'),
  ('animálico', '142,75,19'),
  ('pachulí', '99,101,46'),
  ('iris', '183,167,215'),
  ('gourmand', '240,203,122'),
  ('ahumado', '130,116,135'),
  ('balsámico', '173,131,89'),
  ('terrosos', '84,72,56'),
  ('canela', '210,105,30'),
  ('oud', '84,65,54'),
  ('metálico', '151,176,183'),
  ('caramelo', '221,163,86'),
  ('rosas', '254,1,107'),
  ('cuero', '120,72,58')
on conflict (name) do update set color_rgb = excluded.color_rgb;

insert into public.perfume_notes (perfume_id, phase, position, note_name) values
  ('sauvage', 'salida', 1, 'bergamota'),
  ('sauvage', 'corazon', 1, 'pimienta de Sichuan'),
  ('sauvage', 'corazon', 2, 'lavanda'),
  ('sauvage', 'corazon', 3, 'anís estrellado'),
  ('sauvage', 'corazon', 4, 'nuez moscada'),
  ('sauvage', 'fondo', 1, 'ambroxan'),
  ('sauvage', 'fondo', 2, 'vainilla'),
  ('acqua-di-gio', 'salida', 1, 'lima'),
  ('acqua-di-gio', 'salida', 2, 'limón'),
  ('acqua-di-gio', 'salida', 3, 'bergamota'),
  ('acqua-di-gio', 'salida', 4, 'jazmín'),
  ('acqua-di-gio', 'salida', 5, 'naranja'),
  ('acqua-di-gio', 'salida', 6, 'mandarina'),
  ('acqua-di-gio', 'salida', 7, 'neroli'),
  ('acqua-di-gio', 'corazon', 1, 'notas marinas'),
  ('acqua-di-gio', 'corazon', 2, 'jazmín'),
  ('acqua-di-gio', 'corazon', 3, 'calone'),
  ('acqua-di-gio', 'corazon', 4, 'romero'),
  ('acqua-di-gio', 'corazon', 5, 'durazno'),
  ('acqua-di-gio', 'corazon', 6, 'fresia'),
  ('acqua-di-gio', 'corazon', 7, 'jacinto'),
  ('acqua-di-gio', 'corazon', 8, 'violeta'),
  ('acqua-di-gio', 'corazon', 9, 'ciclamen'),
  ('acqua-di-gio', 'corazon', 10, 'cilantro'),
  ('acqua-di-gio', 'corazon', 11, 'rosa'),
  ('acqua-di-gio', 'corazon', 12, 'nuez moscada'),
  ('acqua-di-gio', 'corazon', 13, 'reseda'),
  ('acqua-di-gio', 'fondo', 1, 'almizcle blanco'),
  ('acqua-di-gio', 'fondo', 2, 'cedro'),
  ('acqua-di-gio', 'fondo', 3, 'musgo de roble'),
  ('acqua-di-gio', 'fondo', 4, 'pachulí'),
  ('acqua-di-gio', 'fondo', 5, 'ámbar'),
  ('light-blue', 'salida', 1, 'limón siciliano'),
  ('light-blue', 'salida', 2, 'manzana'),
  ('light-blue', 'salida', 3, 'cedro'),
  ('light-blue', 'salida', 4, 'campanilla'),
  ('light-blue', 'corazon', 1, 'bambú'),
  ('light-blue', 'corazon', 2, 'jazmín'),
  ('light-blue', 'corazon', 3, 'rosa blanca'),
  ('light-blue', 'fondo', 1, 'cedro'),
  ('light-blue', 'fondo', 2, 'almizcle'),
  ('light-blue', 'fondo', 3, 'ámbar'),
  ('dylan-blue', 'salida', 1, 'bergamota de Calabria'),
  ('dylan-blue', 'salida', 2, 'notas acuáticas'),
  ('dylan-blue', 'salida', 3, 'toronja'),
  ('dylan-blue', 'salida', 4, 'hojas de higuera'),
  ('dylan-blue', 'corazon', 1, 'ambroxan'),
  ('dylan-blue', 'corazon', 2, 'pimienta negra'),
  ('dylan-blue', 'corazon', 3, 'pachulí'),
  ('dylan-blue', 'corazon', 4, 'hojas de violeta'),
  ('dylan-blue', 'corazon', 5, 'papiro de Egipto'),
  ('dylan-blue', 'fondo', 1, 'incienso'),
  ('dylan-blue', 'fondo', 2, 'almizcle'),
  ('dylan-blue', 'fondo', 3, 'haba tonka'),
  ('dylan-blue', 'fondo', 4, 'azafrán'),
  ('libre', 'salida', 1, 'lavanda'),
  ('libre', 'salida', 2, 'mandarina'),
  ('libre', 'salida', 3, 'grosellas negras'),
  ('libre', 'salida', 4, 'petit grain'),
  ('libre', 'corazon', 1, 'lavanda'),
  ('libre', 'corazon', 2, 'flor de azahar'),
  ('libre', 'corazon', 3, 'jazmín'),
  ('libre', 'fondo', 1, 'vainilla de Madagascar'),
  ('libre', 'fondo', 2, 'almizcle'),
  ('libre', 'fondo', 3, 'cedro'),
  ('libre', 'fondo', 4, 'ámbar gris'),
  ('la-vie-est-belle', 'salida', 1, 'grosellas negras'),
  ('la-vie-est-belle', 'salida', 2, 'pera'),
  ('la-vie-est-belle', 'corazon', 1, 'iris'),
  ('la-vie-est-belle', 'corazon', 2, 'jazmín'),
  ('la-vie-est-belle', 'corazon', 3, 'flor de azahar'),
  ('la-vie-est-belle', 'fondo', 1, 'praliné'),
  ('la-vie-est-belle', 'fondo', 2, 'vainilla'),
  ('la-vie-est-belle', 'fondo', 3, 'pachulí'),
  ('la-vie-est-belle', 'fondo', 4, 'haba tonka'),
  ('eros', 'salida', 1, 'menta'),
  ('eros', 'salida', 2, 'manzana acaramelada'),
  ('eros', 'salida', 3, 'limón'),
  ('eros', 'salida', 4, 'mandarina'),
  ('eros', 'corazon', 1, 'ambroxan'),
  ('eros', 'corazon', 2, 'geranio'),
  ('eros', 'corazon', 3, 'esclarea'),
  ('eros', 'fondo', 1, 'vainilla'),
  ('eros', 'fondo', 2, 'cedro'),
  ('eros', 'fondo', 3, 'sándalo'),
  ('eros', 'fondo', 4, 'naranja amarga'),
  ('eros', 'fondo', 5, 'pachulí'),
  ('eros', 'fondo', 6, 'cuero'),
  ('bleu-de-chanel', 'salida', 1, 'toronja'),
  ('bleu-de-chanel', 'salida', 2, 'limón'),
  ('bleu-de-chanel', 'salida', 3, 'menta'),
  ('bleu-de-chanel', 'salida', 4, 'pimienta rosa'),
  ('bleu-de-chanel', 'corazon', 1, 'jengibre'),
  ('bleu-de-chanel', 'corazon', 2, 'nuez moscada'),
  ('bleu-de-chanel', 'corazon', 3, 'jazmín'),
  ('bleu-de-chanel', 'corazon', 4, 'Iso E Super'),
  ('bleu-de-chanel', 'fondo', 1, 'incienso'),
  ('bleu-de-chanel', 'fondo', 2, 'cedro'),
  ('bleu-de-chanel', 'fondo', 3, 'vetiver'),
  ('bleu-de-chanel', 'fondo', 4, 'sándalo'),
  ('bleu-de-chanel', 'fondo', 5, 'pachulí'),
  ('bleu-de-chanel', 'fondo', 6, 'ládano'),
  ('bleu-de-chanel', 'fondo', 7, 'almizcle blanco'),
  ('terre-d-hermes', 'salida', 1, 'naranja'),
  ('terre-d-hermes', 'salida', 2, 'toronja'),
  ('terre-d-hermes', 'corazon', 1, 'pimienta'),
  ('terre-d-hermes', 'corazon', 2, 'pelargonio'),
  ('terre-d-hermes', 'corazon', 3, 'sílex'),
  ('terre-d-hermes', 'fondo', 1, 'vetiver'),
  ('terre-d-hermes', 'fondo', 2, 'cedro'),
  ('terre-d-hermes', 'fondo', 3, 'pachulí'),
  ('terre-d-hermes', 'fondo', 4, 'benjuí'),
  ('boss-bottled', 'salida', 1, 'manzana'),
  ('boss-bottled', 'salida', 2, 'ciruela'),
  ('boss-bottled', 'salida', 3, 'bergamota'),
  ('boss-bottled', 'salida', 4, 'limón'),
  ('boss-bottled', 'salida', 5, 'musgo de roble'),
  ('boss-bottled', 'salida', 6, 'geranio'),
  ('boss-bottled', 'corazon', 1, 'canela'),
  ('boss-bottled', 'corazon', 2, 'caoba'),
  ('boss-bottled', 'corazon', 3, 'clavel'),
  ('boss-bottled', 'fondo', 1, 'vainilla'),
  ('boss-bottled', 'fondo', 2, 'sándalo'),
  ('boss-bottled', 'fondo', 3, 'cedro'),
  ('boss-bottled', 'fondo', 4, 'vetiver'),
  ('boss-bottled', 'fondo', 5, 'olivo'),
  ('oud-for-glory', 'salida', 1, 'azafrán'),
  ('oud-for-glory', 'salida', 2, 'nuez moscada'),
  ('oud-for-glory', 'salida', 3, 'lavanda'),
  ('oud-for-glory', 'corazon', 1, 'madera de oud'),
  ('oud-for-glory', 'corazon', 2, 'pachulí'),
  ('oud-for-glory', 'fondo', 1, 'madera de oud'),
  ('oud-for-glory', 'fondo', 2, 'pachulí'),
  ('oud-for-glory', 'fondo', 3, 'almizcle'),
  ('oud-mood', 'salida', 1, 'rosa'),
  ('oud-mood', 'salida', 2, 'azafrán'),
  ('oud-mood', 'salida', 3, 'pimienta de Jamaica'),
  ('oud-mood', 'corazon', 1, 'madera de oud'),
  ('oud-mood', 'corazon', 2, 'caramelo'),
  ('oud-mood', 'corazon', 3, 'notas florales'),
  ('oud-mood', 'corazon', 4, 'pachulí'),
  ('oud-mood', 'fondo', 1, 'notas amaderadas'),
  ('oud-mood', 'fondo', 2, 'ámbar'),
  ('oud-mood', 'fondo', 3, 'incienso'),
  ('oud-mood', 'fondo', 4, 'resinas'),
  ('oud-mood', 'fondo', 5, 'almizcle'),
  ('1-million', 'salida', 1, 'mandarina roja'),
  ('1-million', 'salida', 2, 'toronja'),
  ('1-million', 'salida', 3, 'menta'),
  ('1-million', 'corazon', 1, 'canela'),
  ('1-million', 'corazon', 2, 'notas especiadas'),
  ('1-million', 'corazon', 3, 'rosa'),
  ('1-million', 'fondo', 1, 'ámbar'),
  ('1-million', 'fondo', 2, 'cuero'),
  ('1-million', 'fondo', 3, 'notas amaderadas'),
  ('1-million', 'fondo', 4, 'pachulí hindú'),
  ('coco-mademoiselle', 'salida', 1, 'naranja'),
  ('coco-mademoiselle', 'salida', 2, 'mandarina'),
  ('coco-mademoiselle', 'salida', 3, 'bergamota'),
  ('coco-mademoiselle', 'salida', 4, 'flor de azahar'),
  ('coco-mademoiselle', 'corazon', 1, 'rosa turca'),
  ('coco-mademoiselle', 'corazon', 2, 'jazmín'),
  ('coco-mademoiselle', 'corazon', 3, 'mimosa'),
  ('coco-mademoiselle', 'corazon', 4, 'ylang-ylang'),
  ('coco-mademoiselle', 'fondo', 1, 'pachulí'),
  ('coco-mademoiselle', 'fondo', 2, 'almizcle blanco'),
  ('coco-mademoiselle', 'fondo', 3, 'vainilla'),
  ('coco-mademoiselle', 'fondo', 4, 'vetiver'),
  ('coco-mademoiselle', 'fondo', 5, 'haba tonka'),
  ('coco-mademoiselle', 'fondo', 6, 'opopónaco')
on conflict (perfume_id, phase, position) do update set note_name = excluded.note_name;

insert into public.perfume_accords (perfume_id, position, accord_name, intensity) values
  ('sauvage', 1, 'fresco especiado', 100),
  ('sauvage', 2, 'cítrico', 82),
  ('sauvage', 3, 'ámbar', 72),
  ('sauvage', 4, 'lavanda', 57),
  ('sauvage', 5, 'almizclado', 55),
  ('sauvage', 6, 'aromático', 51),
  ('sauvage', 7, 'herbal', 51),
  ('sauvage', 8, 'anís', 49),
  ('acqua-di-gio', 1, 'cítrico', 100),
  ('acqua-di-gio', 2, 'aromático', 66),
  ('acqua-di-gio', 3, 'marino', 58),
  ('acqua-di-gio', 4, 'fresco especiado', 51),
  ('acqua-di-gio', 5, 'florales', 47),
  ('acqua-di-gio', 6, 'amaderado', 46),
  ('acqua-di-gio', 7, 'fresco', 45),
  ('light-blue', 1, 'cítrico', 100),
  ('light-blue', 2, 'amaderado', 74),
  ('light-blue', 3, 'fresco', 63),
  ('light-blue', 4, 'afrutados', 59),
  ('light-blue', 5, 'aromático', 54),
  ('light-blue', 6, 'almizclado', 49),
  ('light-blue', 7, 'atalcado', 47),
  ('light-blue', 8, 'verde', 44),
  ('dylan-blue', 1, 'ámbar', 100),
  ('dylan-blue', 2, 'cítrico', 92),
  ('dylan-blue', 3, 'fresco especiado', 75),
  ('dylan-blue', 4, 'almizclado', 71),
  ('dylan-blue', 5, 'acuático', 70),
  ('dylan-blue', 6, 'cálido especiado', 65),
  ('dylan-blue', 7, 'amaderado', 54),
  ('dylan-blue', 8, 'fresco', 52),
  ('libre', 1, 'floral blanco', 100),
  ('libre', 2, 'cítrico', 81),
  ('libre', 3, 'lavanda', 75),
  ('libre', 4, 'avainillado', 64),
  ('libre', 5, 'aromático', 57),
  ('libre', 6, 'dulce', 56),
  ('libre', 7, 'atalcado', 53),
  ('libre', 8, 'animálico', 52),
  ('la-vie-est-belle', 1, 'dulce', 100),
  ('la-vie-est-belle', 2, 'avainillado', 82),
  ('la-vie-est-belle', 3, 'afrutados', 66),
  ('la-vie-est-belle', 4, 'pachulí', 58),
  ('la-vie-est-belle', 5, 'amaderado', 58),
  ('la-vie-est-belle', 6, 'floral blanco', 55),
  ('la-vie-est-belle', 7, 'atalcado', 53),
  ('la-vie-est-belle', 8, 'iris', 49),
  ('eros', 1, 'cítrico', 100),
  ('eros', 2, 'aromático', 94),
  ('eros', 3, 'verde', 80),
  ('eros', 4, 'avainillado', 75),
  ('eros', 5, 'amaderado', 73),
  ('eros', 6, 'dulce', 71),
  ('eros', 7, 'fresco especiado', 66),
  ('eros', 8, 'gourmand', 63),
  ('bleu-de-chanel', 1, 'cítrico', 100),
  ('bleu-de-chanel', 2, 'amaderado', 82),
  ('bleu-de-chanel', 3, 'fresco especiado', 80),
  ('bleu-de-chanel', 4, 'aromático', 70),
  ('bleu-de-chanel', 5, 'ámbar', 67),
  ('bleu-de-chanel', 6, 'ahumado', 53),
  ('bleu-de-chanel', 7, 'balsámico', 50),
  ('bleu-de-chanel', 8, 'cálido especiado', 50),
  ('terre-d-hermes', 1, 'cítrico', 100),
  ('terre-d-hermes', 2, 'amaderado', 92),
  ('terre-d-hermes', 3, 'fresco especiado', 79),
  ('terre-d-hermes', 4, 'aromático', 77),
  ('terre-d-hermes', 5, 'terrosos', 60),
  ('terre-d-hermes', 6, 'cálido especiado', 54),
  ('boss-bottled', 1, 'amaderado', 100),
  ('boss-bottled', 2, 'afrutados', 91),
  ('boss-bottled', 3, 'avainillado', 79),
  ('boss-bottled', 4, 'cálido especiado', 79),
  ('boss-bottled', 5, 'canela', 69),
  ('boss-bottled', 6, 'aromático', 64),
  ('boss-bottled', 7, 'cítrico', 62),
  ('boss-bottled', 8, 'atalcado', 62),
  ('oud-for-glory', 1, 'oud', 100),
  ('oud-for-glory', 2, 'cálido especiado', 94),
  ('oud-for-glory', 3, 'fresco especiado', 87),
  ('oud-for-glory', 4, 'pachulí', 69),
  ('oud-for-glory', 5, 'metálico', 56),
  ('oud-for-glory', 6, 'almizclado', 55),
  ('oud-for-glory', 7, 'amaderado', 53),
  ('oud-for-glory', 8, 'lavanda', 53),
  ('oud-mood', 1, 'ámbar', 100),
  ('oud-mood', 2, 'oud', 71),
  ('oud-mood', 3, 'amaderado', 70),
  ('oud-mood', 4, 'cálido especiado', 69),
  ('oud-mood', 5, 'caramelo', 62),
  ('oud-mood', 6, 'balsámico', 58),
  ('oud-mood', 7, 'rosas', 53),
  ('oud-mood', 8, 'ahumado', 50),
  ('1-million', 1, 'cálido especiado', 100),
  ('1-million', 2, 'canela', 81),
  ('1-million', 3, 'cítrico', 73),
  ('1-million', 4, 'ámbar', 63),
  ('1-million', 5, 'amaderado', 61),
  ('1-million', 6, 'cuero', 57),
  ('1-million', 7, 'rosas', 53),
  ('1-million', 8, 'animálico', 50),
  ('coco-mademoiselle', 1, 'cítrico', 100),
  ('coco-mademoiselle', 2, 'amaderado', 63),
  ('coco-mademoiselle', 3, 'pachulí', 62),
  ('coco-mademoiselle', 4, 'dulce', 62),
  ('coco-mademoiselle', 5, 'floral blanco', 60),
  ('coco-mademoiselle', 6, 'rosas', 53),
  ('coco-mademoiselle', 7, 'terrosos', 49),
  ('coco-mademoiselle', 8, 'avainillado', 48)
on conflict (perfume_id, position) do update set accord_name = excluded.accord_name, intensity = excluded.intensity;

insert into public.perfume_usage (perfume_id, winter, spring, summer, autumn, day_score, night_score) values
  ('sauvage', 92, 99, 83, 100, 94, 98),
  ('acqua-di-gio', 10, 69, 100, 19, 93, 20),
  ('light-blue', 11, 55, 100, 12, 94, 12),
  ('dylan-blue', 43, 98, 100, 79, 97, 75),
  ('libre', 82, 77, 46, 100, 91, 84),
  ('la-vie-est-belle', 100, 56, 31, 86, 86, 87),
  ('eros', 84, 100, 81, 92, 88, 97),
  ('bleu-de-chanel', 57, 98, 91, 84, 100, 87),
  ('terre-d-hermes', 50, 94, 74, 92, 100, 54),
  ('boss-bottled', 55, 91, 53, 88, 100, 55),
  ('oud-for-glory', 100, 37, 15, 87, 39, 90),
  ('oud-mood', 100, 35, 18, 90, 46, 89),
  ('1-million', 99, 35, 20, 84, 40, 100),
  ('coco-mademoiselle', 69, 86, 49, 81, 100, 68)
on conflict (perfume_id) do update set winter = excluded.winter, spring = excluded.spring, summer = excluded.summer, autumn = excluded.autumn, day_score = excluded.day_score, night_score = excluded.night_score;

update public.perfume_notes data set source_id = source.id
from public.perfume_sources source
where source.perfume_id = data.perfume_id and source.is_primary and source.publisher = 'Fragrantica';

update public.perfume_accords data set source_id = source.id
from public.perfume_sources source
where source.perfume_id = data.perfume_id and source.is_primary and source.publisher = 'Fragrantica';

update public.perfume_usage data set source_id = source.id
from public.perfume_sources source
where source.perfume_id = data.perfume_id and source.is_primary and source.publisher = 'Fragrantica';
